# Site
repository: akorkovelos/akorkovelos.github.io
favicon: images/favicon.ico

# Google Analytics
google_analytics: UA-145086259-1

# Personal info
name: Alexandros Korkovelos
title: Geospatial Data Analyst
email: alex.lari.kor@gmail.com
phone: 0046 735 84 36 13
#website: 

# Social links
linkedin_username: alexandros-korkovelos-07931168
github_username: akorkovelos
cv_link: Alexandros Korkovelos CV.pdf

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/avataars.png
about_content: | # this will include new lines to allow paragraphs. This supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>. 
 I am an enthusiastic geospatial data analyst currently leading the [Sustainable Energy for All](https://www.kth.se/en/itm/inst/energiteknik/forskningsavdelningar/desa) team at KTH. My work focuses on linking Geographic Information  Systems  (GIS)  and  energy  systems models to support planning and policy development for rural electrification. 
 Over the past years I have been working on enhancing key components of the [OnSSET](http://www.onsset.org/) model as well as coordinating (or supporting) several projects with key partners such as the World Bank, UNDESA, IEA, UNECA, SNV and ABB.

 I am highly motivated by the great potential of <mark>big data</mark>, <mark>remote sensing</mark> & <mark>data science</mark> in supporting solutions towards
 sustainable development. Thus, very interested in expanding my technical and analytical skills in these areas and dedicate my work on tackling complex problems of our world.

 **Expertise:** Geospatial analysis, energy access, electrification planning, capacity building & knowledge transfer
 

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)

more_content: | # this will include new lines to allow paragraphs
  
  Old school millenial that thrives in experiences, values equality and strives for - self and global - awareness. 
  Always taking opportunities to expand skills and broaden mindset. I really enjoy meeting people that are passionate about their work and interests and want to make a difference. 
  In my spare time I code, train and cook; I also like reading and discussing about history, political economy and geo-politics. 
  

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
