# Site
repository: akorkovelos/akorkovelos.github.io
favicon: images/favicon.ico

# Personal info
name: Alexandros Korkovelos
title: Geospatial Data Analyst
email: alex.lari.kor@gmail.com
#phone: 0046 735 84 36 13
website: akorkovelos.me

# Social links
linkedin_username: alexandros-korkovelos-07931168
github_username: akorkovelos

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/avataars.png
about_content: | # this will include new lines to allow paragraphs. This supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>. 
 Geospatial data analyst, highly motivated by the great potential of <mark>remote sensing</mark>, <mark>big data</mark> & <mark>geospatial analysis</mark> in supporting innovation towards
 sustainable development. Interested in a role of data scientist through which I can use and further develop my technical and analytical skills to
 provide strategic advice and insights to complex problems.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies are:

    - Geo-politics
    - Political history
    - Aviation
    - Travelling
    - Crossfit
    - Indoor gardening


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
